alias zipc_prod="ssh jvu@dev2-zip-web1.zc2.zynga.com"
alias zipc_dev="ssh jvu@dev2-zip-web4.zc2.zynga.com"
alias vc_prod="ssh jvu@dev2-zip-web6.zc2.zynga.com"
alias vc_dev="ssh jvu@dev2-zip-web4.zc2.zynga.com"
alias ztm_front_end="ssh jvu@dev2-zip-web3.zc2.zynga.com"
alias reverse_lemmatizer="ssh jvu@dev2-zip-web3.zc2.zynga.com"
alias ztm_back_end="ssh jvu@dev2-zip-web7.zc2.zynga.com"
